//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyGym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.COMENTARIO = new HashSet<COMENTARIO>();
            this.CONTACTO = new HashSet<CONTACTO>();
        }
    
        public int ID_CLIENTE { get; set; }
        public string CI_CLIENTE { get; set; }
        public int ID_LOGIN { get; set; }
        public string NOMBRE_CLI { get; set; }
        public string APELLIDO_CLI { get; set; }
        public string DIRECCION_CLI { get; set; }
        public int EDAD_CLI { get; set; }
        public string TELF_CLI { get; set; }
        public string GENERO_CLI { get; set; }
        public string SECTOR_CLI { get; set; }
    
        public virtual ACCESO ACCESO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMENTARIO> COMENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACTO> CONTACTO { get; set; }
    }
}
