//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyGym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMENTARIO
    {
        public int ID_COMENTARIO { get; set; }
        public int ID_GIMNASIO { get; set; }
        public int CI_CLIENTE { get; set; }
        public string TITULO_COMEN { get; set; }
        public string DESCRIPCION_COMEN { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual GIMNASIO GIMNASIO { get; set; }
    }
}
