//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyGym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIMNASIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIMNASIO()
        {
            this.COMENTARIOs = new HashSet<COMENTARIO>();
            this.CONTACTOes = new HashSet<CONTACTO>();
        }
    
        public int ID_GIMNASIO { get; set; }
        public int ID_CATEGORIA { get; set; }
        public string NOMBRE_GIMNASIO { get; set; }
        public string DIRECCION_GIMANSIO { get; set; }
        public string DESCRIPCION_GIMASIO { get; set; }
        public decimal PRECIO_ANUAL { get; set; }
        public decimal PRECIO_MENSUAL { get; set; }
        public string TELF_GIMNASIO { get; set; }
        public string SECTOR_GIMNASIO { get; set; }
        public string IMAGEN_GIMNASIO { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMENTARIO> COMENTARIOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACTO> CONTACTOes { get; set; }
    }
}
